# Generated by Django 3.1 on 2020-08-17 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formname', models.CharField(max_length=255, null=True, verbose_name='FormName:')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formy.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswerFieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=4000, null=True)),
                ('formanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formy.formanswer')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, null=True, verbose_name='Label')),
                ('name', models.CharField(max_length=255, null=True)),
                ('data_type', models.CharField(max_length=255, null=True)),
                ('form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form')),
            ],
        ),
    ]
