# Generated by Django 3.1 on 2020-08-15 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='form',
        ),
        migrations.RemoveField(
            model_name='coloranswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='dateanswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='emailanswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='telanswer',
            name='field',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='field',
        ),
        migrations.AddField(
            model_name='coloranswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='coloranswer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='coloranswer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='dateanswer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='emailanswer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='emailanswer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='telanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='telanswer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='telanswer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Formy.form', verbose_name='Form'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='label',
            field=models.CharField(max_length=255, null=True, verbose_name='Label'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='telanswer',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='answer',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Field',
        ),
    ]
