# Generated by Django 3.1 on 2020-08-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formy', '0002_auto_20200815_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formy.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormAnswerFieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=4000, null=True)),
                ('formanswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formy.formanswer')),
            ],
        ),
        migrations.RenameModel(
            old_name='TextAnswer',
            new_name='Field',
        ),
        migrations.RemoveField(
            model_name='dateanswer',
            name='form',
        ),
        migrations.RemoveField(
            model_name='emailanswer',
            name='form',
        ),
        migrations.RemoveField(
            model_name='telanswer',
            name='form',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='answer',
            new_name='data_type',
        ),
        migrations.DeleteModel(
            name='ColorAnswer',
        ),
        migrations.DeleteModel(
            name='DateAnswer',
        ),
        migrations.DeleteModel(
            name='EmailAnswer',
        ),
        migrations.DeleteModel(
            name='telAnswer',
        ),
    ]
