# Generated by Django 3.1 on 2020-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formy', '0003_auto_20200816_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='formanswerfielddata',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
